[package]
name = "yew-router"
version = "0.15.0"
authors = ["Hamza <muhammadhamza1311@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["web", "yew", "router"]
categories = ["gui", "web-programming"]
description = "A router implementation for the Yew framework"
repository = "https://github.com/yewstack/yew"

[dependencies]
yew = { path = "../yew", default-features = false }
yew-router-macro = { path = "../yew-router-macro" }

serde = "1.0.126"
wasm-bindgen = { version = "0.2", features = ["serde-serialize"] }
js-sys = "0.3"
weblog = "0.3.0"
gloo = "0.2.1"
route-recognizer = "0.3.0"
regex = "1.5.4"
percent-encoding = "2.1.0"
anymap = "0.12"

[dependencies.web-sys]
version = "0.3"
features = [
    "Attr",
    "Document",
    "History",
    "HtmlBaseElement",
    "Event",
    "NamedNodeMap",
    "Url",
    "UrlSearchParams",
    "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.3"
serde = { version = "1.0", features = ["derive"] }
yew-functional = { path = "../yew-functional" }

[dev-dependencies.web-sys]
version = "0.3"
features = ["HtmlHeadElement"]
